### ISSUE TITLE
_quarto.yml.local is not treated correctly

### ISSUE THREAD

**Issue by frederic-baucher** [frederic-baucher/babelquarto#2]
# PROBLEM
## Context
With such a _quarto.yml.local
```yml
website:
  navbar:
    left:
      - tests.qmd
```
tests.qmd
```yml
title: Tests entries
```

tests.fr.qmd
```yml
---
title: Entrée de tests
---
```

## Expected
in EN, navbar
Tests entries
FR command links to fr/tests.fr.html
in FR, navbar
Entrée de tests

## Observed
in EN, navbar
Tests entries
in FR, navbar
Tests entries
